{{- if .Values.serviceAccount.operator.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "model-fleet.operatorSA" . }}
  labels: {{- include "model-fleet.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.serviceAccount.operator.annotations | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
{{- if .Values.controlPlane.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "model-fleet.controlPlaneSA" . }}
  labels: {{- include "model-fleet.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
{{- if and .Values.slack.enabled .Values.serviceAccount.slack.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "model-fleet.slackSA" . }}
  labels: {{- include "model-fleet.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.serviceAccount.slack.annotations | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
